<link rel="stylesheet" href="{{ asset('bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/font-awesome/css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/lato/css/lato.min.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bootstrap-table/dist/bootstrap-table.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/select2/dist/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/morris.js/morris.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css') }}">
<link rel="stylesheet" href="{{ asset('css/emprunt.css') }}">
<link rel="stylesheet" href="{{ asset('css/fonts.css') }}">