<script type="application/javascript"
        src="{{ asset('bower_components/jquery/dist/jquery.min.js') }}"></script>
<script type="application/javascript"
        src="{{ asset('bower_components/tableExport.jquery.plugin/tableExport.min.js') }}"></script>
<script type="application/javascript"
        src="{{ asset('bower_components/restfulizer/jquery.restfulizer.js') }}"></script>
<script type="application/javascript"
        src="{{ asset('bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script type="application/javascript"
        src="{{ asset('bower_components/bootstrap-table/dist/bootstrap-table.min.js') }}"></script>
<script type="application/javascript"
        src="{{ asset('bower_components/bootstrap-table/dist/locale/bootstrap-table-fr-FR.min.js') }}"></script>
<script type="application/javascript"
        src="{{ asset('bower_components/bootstrap-table/dist/extensions/export/bootstrap-table-export.js') }}"></script>
<script type="application/javascript"
        src="{{ asset('bower_components/select2/dist/js/select2.min.js') }}"></script>
<script type="application/javascript"
        src="{{ asset('bower_components/select2/dist/js/i18n/fr.js') }}"></script>
<script type="application/javascript"
        src="{{ asset('js/emprunt.js') }}"></script>